review_api/views/portal.py
from flask import Blueprint, abort, session, render_template, request, redirect, url_for

from review_api.helpers import security, redditauth
from review_api.models import ApiUser, Meta, Status, Role, Session
from review_api.config import config

blueprint = Blueprint('portal', __name__, template_folder='templates')

@blueprint.route('/')
def home():
    user, username, auth_url = None, None, None
    if redditauth.is_authorised(session):
        username = session['username']
        user = ApiUser.find(session['username'])
    else:
        auth_url = redditauth.make_auth_url(session)
    return render_template('portal/index.html', base_url=config.BASE_URL, auth_url=auth_url, user=user, username=username)

@blueprint.route('/changelog')
def changelog():
    user, username, auth_url = None, None, None
    if redditauth.is_authorised(session):
        username = session['username']
        user = ApiUser.find(session['username'])
    else:
        auth_url = redditauth.make_auth_url(session)
    return render_template('portal/changelog.html', base_url=config.BASE_URL, auth_url=auth_url, user=user, username=username)

@blueprint.route('/user')
def user():
    if not redditauth.is_authorised(session):
        return redirect(url_for('portal.home'))
    username = session['username']
    user = ApiUser.find(username)
    if not user:
        return render_template('portal/register.html', username=username, user=user)
    return render_template('portal/user.html', user=user)

@blueprint.route('/user/register', methods=['POST'])
def registration():
    if not redditauth.is_authorised(session):
        return abort(401)
    username = session['username']
    password = request.form['password']
    if ApiUser.register(username, password):
        return redirect(url_for('portal.user'))
    else:
        abort(500)

@blueprint.route('/user/change_password', methods=['POST'])
def change_password():
    if not redditauth.is_authorised(session):
        return abort(401)
    username = session['username']
    password = request.form['password']
    ApiUser.update_password(username, password)
    return redirect(url_for('portal.user'))

@blueprint.route('/admin/')
def admin():
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)

    limit = 10
    users = ApiUser.newest(limit=limit)
    statuss = [status.name for status in Status]
    api_version = Meta.find('api_version')
    meta = {'api': 1}
    if api_version:
        meta['api'] = api_version.value
    return render_template('portal/admin.html', user=user, users=users, statuss=statuss, meta=meta)

@blueprint.route('/admin/users/', defaults={'page': 1})
@blueprint.route('/admin/users/<int:page>')
def admin_users(page):
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)

    limit = 10
    offset = (page - 1) * limit
    users = ApiUser.newest(limit=limit, offset=offset)
    statuss = [status.name for status in Status]
    return render_template('portal/admin_users.html', user=user, users=users, statuss=statuss)

@blueprint.route('/admin/users/<name>')
def admin_user(name):
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)

    api_user = ApiUser.find(username=name.lower())
    if not api_user:
        abort(404)

    statuss = [status.name for status in Status]
    return render_template('portal/admin_user.html', user=user, api_user=api_user, statuss=statuss)

@blueprint.route('/admin/process_registration', methods=['POST'])
def process_registration():
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)

    usernames = request.form.getlist('usernames[]')
    approvals = request.form.getlist('approvals[]')
    db_session = Session()
    for index, username in enumerate(usernames):
        db_session.query(ApiUser)\
            .filter(ApiUser.username == username)\
            .update({'status': approvals[index]})

    db_session.commit()
    return redirect(url_for('portal.admin'))

@blueprint.route('/admin/update_meta', methods=['POST'])
def update_meta():
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)
    
    Meta.update(request.form['key'], request.form['value'])
    return redirect(request.referrer)

@blueprint.route('/reddit')
def reddit_callback():
    error = request.args.get('error', '')
    if error:
        return "Error: " + error
    state = request.args.get('state', '')
    if not state in session:
        abort(400)
    session.pop(state)
    code = request.args.get('code')
    session['access_token'] = redditauth.get_token(code)
    return redirect(url_for('portal.user'))    

@blueprint.route('/logout')
def logout():
    try:
        session.pop('username')
        session.pop('access_token')
    except KeyError:
        pass
    return redirect(url_for('portal.home'))

review_api/templates/portal/admin.html
{% extends 'layout.html' %}
{% block title %} {{ user.display_name}} {%endblock%}
{% block subtitle %} Admin {% endblock %}
{% block content %}
<div class="section row">
    <div class="large-9 medium-7 small-12 columns">
        <h3>Hi, {{ user.display_name }}!</h3>
        <p>
            You can manage API user access below.
        </p>
    </div>
    <div class="large-3 medium-5 small-12 columns">
        <h3>API Version</h3>
        <form method="POST" action="{{ url_for('portal.update_meta') }}">
        <table><tr class="no-border">
        <td>
            <input name="key" type="hidden" value="api_version" />
            <input name="value" type="number" value="{{meta.api}}" class="full" />
        </td>
        <td>
            <input type="submit" value="Submit" />
        </td>
        </tr>
        </table>

        </form>
    </div>
</div>
<div class="section row">
    
    <div class="large-12  columns">
        <h3>Newest registrations<a class="anchor" href="{{url_for('portal.admin_users')}}">  &#8704;</a></h3>

        <form method="POST" action="{{ url_for('portal.process_registration') }}">
            <table>
                <thead><tr><td>Username</td><td class="hide_small">Registration date</td><td>Status</td></tr></thead>
                <tbody>
                {% for api_user in users %}
                    <tr>
                        <td>
                            <a href="{{url_for('portal.admin_user', name=api_user.display_name) }}">{{api_user.display_name }}</a>
                        </td>
                        <td class="hide_small">
                            {{ api_user.created_at }}
                        </td>
                        <td>
                            <input type="hidden" name="usernames[]" value="{{ api_user.username }}" />
                            <select name="approvals[]" class="full">
                                {% for status in statuss %}
                                    <option value="{{ status }}" {% if status == api_user.status %} selected {% endif %}>{{ status.title() }}</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                    <td></td>
                    <td class="hide_small"></td>
                    <td><input type="submit" value="Submit" /></td>
                </tfoot>
            </table>
        </form>
    </div>
</div>
{% endblock %}

review_api/templates/portal/admin_user.html
{% extends 'layout.html' %}
{% block title %} Admin - {{ api_user.display_name}} {%endblock%}
{% block subtitle %} {{ api_user.display_name }} {% endblock %}
{% block content %}
<div class="section row">
    <div class="large-12  columns">
        <h3>Information</h3>

        <form method="POST" action="{{ url_for('portal.process_registration') }}">
            <table>
                <thead><td class="hide_small">Registration date</td><td>Last API request</td><td>Status</td></tr></thead>
                <tbody>
                    <tr>
                        <td class="hide_small">
                            {{ api_user.created_at }}
                        </td>
                        <td>
                            {{ api_user.last_request }}
                        </td>
                        <td>
                            <input type="hidden" name="usernames[]" value="{{ api_user.username }}" />
                            <select name="approvals[]" class="full">
                                {% for status in statuss %}
                                    <option value="{{ status }}" {% if status == api_user.status %} selected {% endif %}>{{ status.title() }}</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <td class="hide_small"></td>
                    <td></td>
                    <td><input type="submit" value="Submit" /></td>
                </tfoot>
            </table>
        </form>
    </div>
</div>
{% endblock %}

review_api/templates/portal/admin_users.html
{% extends 'layout.html' %}
{% block title %} {{ user.display_name}} {%endblock%}
{% block subtitle %} Admin {% endblock %}
{% block content %}
<div class="section row">
    
    <div class="large-12  columns">
        <h3>API Users</h3>

        <form method="POST" action="{{ url_for('portal.process_registration') }}">
            <table>
                <thead><tr><td>Username</td><td class="hide_small">Last request</td><td>Status</td></tr></thead>
                <tbody>
                {% for api_user in users %}
                    <tr>
                        <td>
                            <a href="{{url_for('portal.admin_user', name=api_user.display_name) }}">{{api_user.display_name }}</a>
                        </td>
                        <td class="hide_small">
                            {{ api_user.last_request }}
                        </td>
                        <td>
                            <input type="hidden" name="usernames[]" value="{{ api_user.username }}" />
                            <select name="approvals[]" class="full">
                                {% for status in statuss %}
                                    <option value="{{ status }}" {% if status == api_user.status %} selected {% endif %}>{{ status.title() }}</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                    <td></td>
                    <td class="hide_small"></td>
                    <td><input type="submit" value="Submit" /></td>
                </tfoot>
            </table>
        </form>
    </div>
</div>
{% endblock %}

review_api/templates/portal/changelog.html
{% extends 'layout.html' %}

{% block subtitle %} Changelog {% endblock %}
{% block content %}
<div class="section row">
    <div class="large-12 columns">
        Below is an overview of the changes made to the API.
        <div id="V5" class="section">
            <h3>2016 / 04 / 25<a class="anchor" href="#V5">&#182;</a></h3>
            <ul>
                <li>The offset parameter is now independent of the limit parameter. It no longer skips <span class="inline_code">offset * limit</span> results, but only <span class="inline_code">offset</span> results.</li>
            </ul>
        </div>
        <div class="section" id="V4">
            <h3>2016 / 04 / 20<a class="anchor" href="#V4">&#182;</a></h3>
            <ul>
                <li>Defined default sort order for reviews (first by date, then by bottle id).</li>
                <li>The reviewer by id endpoint has been removed. Reddit usernames that existed solely of numerical values caused problems.</li>
            </ul>
        </div>
        <div class="section" id="V3">
            <h3>2016 / 04 / 19<a class="anchor" href="#V3">&#182;</a></h3>
            <ul>
                <li>Fixed the JSON encoding of results.</li>
                <li>Added endpoints to get reviews by Reviewer and Subreddit</li>
            </ul>
        </div>
        <div class="section" id="V2">
            <h3>2016 / 04 / 16<a class="anchor" href="#V2">&#182;</a></h3>
            <ul>
                <li>Show a message when the token is expired.</li>
                <li>Add HTTP expiration header for token requests.</li>
            </ul>
        </div>
        <div id="V1">
            <h3>2016 / 04 / 14<a class="anchor" href="#V1">&#182;</a></h3>
            <ul>
                <li>First live version of the API</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

review_api/templates/portal/index.html
{% extends 'layout.html' %}

{% block subtitle %} Documentation {% endblock %}
{% block content %}
<div class="section row">
    <div class="large-12 columns">
        <p>
            The Review API was originally created to decouple the data and the logic from <a href="https://reddit.com/u/review_bot" target="_blank">ReviewBot</a>. Since we were creating an API, we figured others might want to make use of it as well.
            The rest of this document explains how to get access and what data is available.
        </p>

        <p>In a nutshell, this API offers all information pertaining to reviews posted on the subreddits <a href="https://reddit.com/r/scotch" target="_blank">/r/Scotch</a>, <a href="https://reddit.com/r/bourbon" target="_blank">/r/Bourbon</a> and <a href="https://reddit.com/r/worldwhisky" target="_blank">/r/WorldWhisky</a>. Once every few weeks the database is updated using their official archive.
        </p>

        <h3 id="api-access">API Access <a href="#api-access" class="anchor">&#182;</a></h3>
        <p>
            The server uses HTTP Basic Authentication to authenticate a user for the first time. If the authentication is successful, a <a href="https://jwt.io" target="_blank" title="JSON Web Token">JWT</a> is sent back. Subsequent requests should then have this token attached to the HTTP Authorization header. The server validates the token, if it has expired it returns with status 401 and a JSON response (shown below). If the token is valid, the requested data is returned.
        </p>
        <pre>{
    "reason": "expired token"
}</pre>

        <h3 id="create-account">Creating an account <a href="#create-account" class="anchor">&#182;</a></h3>
        <p>
            In order to create an account, you first need to login via Reddit. Since this API contains only data specific to a few subreddits, we believe it should not matter for you to need to login via Reddit. This step makes it easier for us to keep track of who is using the API and to contact anyone in case we need to.
        </p>
        <p>
            Once logged in, you are redirected to the registration page. Your username will always match your Reddit username, but you should use a different password for the API. In case you clicked this page away, no worries. Whenever you are logged in and have not yet registered an API account, you can click on <a title="Review API: Create account" href="{{ url_for('portal.user') }}">Create account</a> in the top right corner to proceed registration.
        </p>
        <p>
            Once you have registered, you will notice that your account status is set to <span class="inline_code">pending</span>. For the time being, we want to manually approve new registrations as our hosting is very limited. We will either send you a message on Reddit or you can check back within a week to see if your account has been approved. Once it has been approved, you can start using the API using the process described in the section below.
        </p>
        <p>
            Note: in case you ever forget your API password, just login to this portal again and you can reset it immediately!
        </p>

        <h3 id="auth-flow">Authentication flow <a href="#auth-flow" class="anchor">&#182;</a></h3>
        <p>
            Let's assume in this example your username is <span class="inline_code">Bob</span> and your API password is <span class="inline_code">Password2</span>. To demonstrate the connection, I'll use Python. 
        </p>
        <p>
            So first off, we need to retrieve a JWT. We can do this by sending a GET request to <span class="inline_code">/auth/token</span> with Basic authentication in the Authorization header.
        </p>
        <pre>import json, requests
url = '{{ base_url }}'
response = requests.get(url + '/auth/token', auth=requests.auth.HTTPBasicAuth('Bob', 'Password2'))
data = json.loads(response.content.decode('utf-8'))
token = data['token']</pre>
        <p>
            Next we can send requests to the API by adding the token the Authorization header. <br /><b>Note:</b> please make sure to add the string <span class="inline_code">'Bearer '</span> in front of the token.
        </p>
        <pre>latest_reviews = requests.get(url + '/api/reviews/', headers={'Authorization': 'Bearer ' + token})</pre>
        <p>And that's all!</p>
        <h3 id="resources">Resources <a href="#resources" class="anchor">&#182;</a></h3>
        <p>
            Reviews are saved in relation to the bottle and the reviewer. Using the API you can request any of these three resources. All endpoints return data in JSON format.
        </p>

        <h4>Global optional parameters</h4>
        <p>First let me point out that by default you get the maximum number of results per request (500). If you need less results, you can use the GET parameter <span class="inline_code">limit=&lt;number&gt;</span> to request just <i>number</i> results. If you want the next <i>number</i> of results you can use the GET parameter <span class="inline_code">offset=&lt;offset&gt;</span>. The <i>offset</i> parameter defaults to zero, so getting results 501 to 750 would look like this: <span class="inline_code">/api/&lt;resource&gt;/?offset=500&amp;limit=250</span>.</p>

        <h4>Common endpoints</h4>
        <p>
            Each resource collection can be requested via <span class="inline_code">/api/&lt;resource&gt;/</span><span class="small">*</span>, where &lt;resource&gt; is one of <u>bottles</u>, <u>reviews</u> or <u>reviewers</u>. A specific resource can be retrieved by appending the id: <span class="inline_code">/api/&lt;resource&gt;/&lt;id&gt;</span>.
        </p>
        <p class="small">*Note the trailing slash.</p>

        <h4>Bottles</h4>
        <p><span class="inline_code">/api/bottles/&lt;id&gt;</span> is the endpoint to get a specific bottle. When you append <span class="inline_code">/reviews/</span>, you'll get all the reviews about this bottle. If you want to directly get all the reviewers of a certain bottle, you can append <span class="inline_code">/reviewers/</span>.

        <h4>Reviewers</h4>
        <p>Reviewer resources are a bit different, you can use the Reddit username of the reviewer instead of the id to retrieve a specific one. As with the bottles, appending <span class="inline_code">/reviews/</span> will return all the reviews by the specified reviewer. Likewise for the bottles: append <span class="inline_code">/bottles/</span> to retrieve all the bottles a reviewer has reviewed.</p>

        <h4>Reviews</h4>
        <p>Additionally, wherever you can request a collection of reviews, you can append <span class="inline_code">/by_subreddit/&lt;subreddit&gt;</span> to only get reviews from one subreddit.</p>

        <h4>Metadata</h4>
        <p>In case you are interested in when the data has been updated for the last time or if the API has had updates, you can query <span class="inline_code">/api/meta</span>. Whenever the API gets an update, details will be published on the <a href="{{ url_for('portal.changelog') }}">Changelog</a> page. The metadata endpoint is public, so you do not need to add your token to the Authorization header. The JSON returned looks similar to this:</p>
        <pre>{
  "api_update": 1460494200,
  "api_version": 1,
  "database_update": 1460373816
}</pre>

        <h3 id="endpoints">Endpoint overview <a href="#endpoints" class="anchor">&#182;</a></h3>
        <p>Below is an overview of all the available API endpoints.</p>

        <h4>Public</h4>
        <p>The endpoints that do not require any authentication.</p>
        <pre>/api/meta</pre>

         <h4>Authentication required</h4>
         <p>These endpoints require a valid JWT in the Authorization header. How to acquire a JWT is described <a href="{{ url_for('portal.home') }}#auth-flow">above</a>.</p>
         <pre>
/api/reviews/
/api/reviews/by_subreddit/&lt;subreddit&gt;
/api/reviews/&lt;id&gt;

/api/bottles/
/api/bottles/&lt;id&gt;
/api/bottles/&lt;id&gt;/reviews/
/api/bottles/&lt;id&gt;/reviewers/

/api/reviewers/
/api/reviewers/&lt;name&gt;
/api/reviewers/&lt;name&gt;/bottles/
/api/reviewers/&lt;name&gt;/reviews/
/api/reviewers/&lt;name&gt;/reviews/by_subreddit/&lt;subreddit&gt;
</pre>

        <h3 id="closing-comments">Closing comments <a href="#closing-comments" class="anchor">&#182;</a></h3>
        <p>That's all for now. If you have any questions, bug reports or feature requests, feel free to send <a href="https://www.reddit.com/user/FlockOnFire/">/u/FlockOnFire</a> a message on Reddit!</p>

        <h3 id="FAQ">FAQ <a href="#FAQ" class="anchor">&#182;</a></h3>
        <h4>What's up with the weird domain?</h4>
        <p>This is a personal domain, mostly used for small project or just linking ip addresses to a domain. If this project proves to be popular, I'll make sure to register a proper domain name!</p>
        
    </div>
</div>
{% endblock %}

review_api/templates/portal/register.html
{% extends 'layout.html' %}
{% block title %}Registration{% endblock %}
{% block subtitle %}Register an API Account{% endblock %}
{% block content %}
<div class="row section">
    <div class="large-12 columns">
        <p>In order to make user of the API, enter a new password below. Your username for the account will be identical to your Reddit Username.</p>
        <form method="POST" action="{{ url_for('portal.registration') }} ">
            <input type="text" value="{{ username }}" readonly />
            <input type="password" name="password" placeholder="password*" pattern="\S{4,}" title="Your password should contain at least 4 characters." required />
            <input type="submit" value="register">
        </form>
        <p class="small">*This password should be different from the one you use at Reddit!</p>
    </div>
</div>
{% endblock %}

review_api/templates/portal/user.html
{% extends 'layout.html' %}
{% block title %} {{ user.display_name}} {%endblock%}
{% block subtitle %} Portal {% endblock %}
{% block content %}
<div class="section row">
    <div class="large-12 columns">
        <p>Hi, {{ user.display_name }}!</p>
        <p>
            Your registration status is: <mark class="{{user.status}}">{{ user.status }}</mark>. 
            {% if user.status == 'approved' %}
                You have access to the API!
            {% endif %}
        </p>
    </div>
</div>
<div class="section row">
    <div class="large-12 columns">
        <h3>Change password</h3>
        <form method="POST" action="{{ url_for('portal.change_password') }}">
            <input type="text" value="{{ user.display_name }}" readonly />
            <input type="password" name="password" placeholder="new password" pattern="\S{4,}" title="Your password should contain at least 4 characters." required />
            <input type="submit" value="Change" />
        </form>
    </div>
</div>
{% endblock %}