review_api/views/errors.py
from flask import make_response, jsonify, render_template
from review_api import app
from jose.exceptions import ExpiredSignatureError
from werkzeug.exceptions import HTTPException
from sqlalchemy.exc import OperationalError

@app.errorhandler(ExpiredSignatureError)
def token_expired(error):
    return make_response(jsonify({'reason': "expired token"}), 401)

@app.errorhandler(HTTPException)
def http_error(error):
    return render_template('error.html', status=error.code, message=error.description, user=None), error.code

@app.errorhandler(OperationalError)
def sql_error(error):
    msg = 'The database is currently being updated. This means you cannot register or change your password at the moment. Please try again later.'
    return render_template('error.html', status=423, message=msg, user=None), 423
    

review_api/views/portal.py
from flask import Blueprint, abort, session, render_template, request, redirect, url_for

from review_api.helpers import security, redditauth
from review_api.models import ApiUser, Meta, Status, Role, Session
from review_api.config import config

blueprint = Blueprint('portal', __name__, template_folder='templates')

@blueprint.route('/')
def home():
    user, username, auth_url = None, None, None
    if redditauth.is_authorised(session):
        username = session['username']
        user = ApiUser.find(session['username'])
    else:
        auth_url = redditauth.make_auth_url(session)
    return render_template('portal/index.html', base_url=config.BASE_URL, auth_url=auth_url, user=user, username=username)

@blueprint.route('/changelog')
def changelog():
    user, username, auth_url = None, None, None
    if redditauth.is_authorised(session):
        username = session['username']
        user = ApiUser.find(session['username'])
    else:
        auth_url = redditauth.make_auth_url(session)
    return render_template('portal/changelog.html', base_url=config.BASE_URL, auth_url=auth_url, user=user, username=username)

@blueprint.route('/user')
def user():
    if not redditauth.is_authorised(session):
        return redirect(url_for('portal.home'))
    username = session['username']
    user = ApiUser.find(username)
    if not user:
        return render_template('portal/register.html', username=username, user=user)
    return render_template('portal/user.html', user=user)

@blueprint.route('/user/register', methods=['POST'])
def registration():
    if not redditauth.is_authorised(session):
        return abort(401)
    username = session['username']
    password = request.form['password']
    if ApiUser.register(username, password):
        return redirect(url_for('portal.user'))
    else:
        abort(500)

@blueprint.route('/user/change_password', methods=['POST'])
def change_password():
    if not redditauth.is_authorised(session):
        return abort(401)
    username = session['username']
    password = request.form['password']
    ApiUser.update_password(username, password)
    return redirect(url_for('portal.user'))

@blueprint.route('/admin/')
def admin():
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)

    limit = 10
    users = ApiUser.newest(limit=limit)
    statuss = [status.name for status in Status]
    api_version = Meta.find('api_version')
    meta = {'api': 1}
    if api_version:
        meta['api'] = api_version.value
    return render_template('portal/admin.html', user=user, users=users, statuss=statuss, meta=meta)

@blueprint.route('/admin/users/', defaults={'page': 1})
@blueprint.route('/admin/users/<int:page>')
def admin_users(page):
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)

    limit = 10
    offset = (page - 1) * limit
    users = ApiUser.newest(limit=limit, offset=offset)
    statuss = [status.name for status in Status]
    return render_template('portal/admin_users.html', user=user, users=users, statuss=statuss)

@blueprint.route('/admin/users/<name>')
def admin_user(name):
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)

    api_user = ApiUser.find(username=name.lower())
    if not api_user:
        abort(404)

    statuss = [status.name for status in Status]
    return render_template('portal/admin_user.html', user=user, api_user=api_user, statuss=statuss)

@blueprint.route('/admin/process_registration', methods=['POST'])
def process_registration():
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)

    usernames = request.form.getlist('usernames[]')
    approvals = request.form.getlist('approvals[]')
    db_session = Session()
    for index, username in enumerate(usernames):
        db_session.query(ApiUser)\
            .filter(ApiUser.username == username)\
            .update({'status': approvals[index]})

    db_session.commit()
    return redirect(url_for('portal.admin'))

@blueprint.route('/admin/update_meta', methods=['POST'])
def update_meta():
    if not redditauth.is_authorised(session):
        abort(401)

    user = ApiUser.find(session['username'])
    if user.role != Role.admin.name:
        abort(403)
    
    Meta.update(request.form['key'], request.form['value'])
    return redirect(request.referrer)

@blueprint.route('/reddit')
def reddit_callback():
    error = request.args.get('error', '')
    if error:
        return "Error: " + error
    state = request.args.get('state', '')
    if not state in session:
        abort(400)
    session.pop(state)
    code = request.args.get('code')
    session['access_token'] = redditauth.get_token(code)
    return redirect(url_for('portal.user'))    

@blueprint.route('/logout')
def logout():
    try:
        session.pop('username')
        session.pop('access_token')
    except KeyError:
        pass
    return redirect(url_for('portal.home'))

review_api/templates/error.html
{% extends 'layout.html' %}

{% block title %}Error {{ status }}{% endblock %}
{% block subtitle %} Error {{ status }} {% endblock %}
{% block content %}
    <div class="row section"><div class="large-12 columns"><p>{{ message }}</p></div></div>
{% endblock %}

review_api/templates/layout.html
<!doctype html>
<html>
<head>
    {% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="API for Whisky Reviews on Reddit.">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8">
    
    <link href='https://fonts.googleapis.com/css?family=Martel:400' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{{ url_for('static', filename='foundation.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>ReviewApi | {% block title %} Portal {% endblock %}</title>

    {% endblock %}
</head>
<body>
    <div class="row">
        <div class="medium-6 small-12 columns">
            <div id="header" class="row">
                <div class="large-12 columns">
                    <h1>Review API</h1>
                </div>
                <div class="large-12 columns">
                    <h2 class="subtitle">{% block subtitle %}{% endblock %}</h2>
                </div>
            </div>
        </div>
        <div class="medium-6 small-12 columns">
            <div id="nav" class="right">
                    <a href="{{ url_for('portal.home') }}">Docs</a>
                {% if user %}
                    <a href="{{ url_for('portal.user') }}">{{ user.display_name }}</a>
                    <a href="{{ url_for('portal.logout') }}">Logout</a>
                {% elif username %}
                    <a href="{{ url_for('portal.user') }}">Create account</a>           
                    <a href="{{ url_for('portal.logout') }}">Logout</a>
                {% elif auth_url %}
                    <a href="{{ auth_url }}">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="footer" class="section row">
        <div class="medium-8 small-8 columns">
            <p class="small">View this and related projects on <a href="https://gitlab.com/r-scotch" target="_blank">GitLab</a></p>
        </div>
            <div class="medium-4 small-4 columns">
                {% if user.role == 'admin' %}
                    <p class="small right"><a href="{{ url_for('portal.admin') }}">Admin</a></p>
                {% else %}
                    <p class="small right"><a href="{{ url_for('portal.changelog') }}">Changelog</a></p>
                {% endif %}
            </div>
    </div>

</body>